#---% Generated by riskcalc: feel free to edit or 'Run App' %---

# Load packages
library(shiny)
library(shinythemes)
library(htmltools)
library(DT)

# Set Google Analytics
ga_tag <- "../google-analytics.html"
if(file.exists(ga_tag)) {
  ga_tag <- includeHTML(ga_tag)
} else {
  ga_tag <- NULL
}
