#---% Generated by riskcalc: feel free to edit or 'Run App' %---
server <-

  # Define the server
  function(input, output, session) {

    # Make a reactive input data frame
    input_data <-
      eventReactive(
        input$run_calculator, {

          # Input validation
          # validate(need(input$input1 > X & input$input1 < Y)) # <--- EDIT AS NEEDED

          # Create input data frame
          # data.frame(Var1 = input$input1, Var2 = input$input2, ...) # <--- EDIT AS NEEDED

        })

    # Show result
    output$result <-
      renderDataTable(
        {

          # Make the data frame containing results
          # data.frame(Result = "Predicted Risk", Value = predict(model, newdata = input_data(), type = "response")) # <--- EDIT AS NEEDED

        },
        options =
          list(
            pageLength = 10,
            lengthMenu = 0,
            searching = 0,
            info = 0,
            paging = 0,
            initComplete =
              DT::JS(
                "function(settings, json) {
                    $(this.api().table().header()).css({'background-color': '#606060', 'color': '#fff'});
                  }"
              )
          ),
        rownames = FALSE
      )

  }
